// packages/web/src/lib/components/EmployeeSelector.svelte
<script lang="ts">
  import { api } from '$lib/api/client'
  import { Input } from '$lib/components/ui/input'
  import { Label } from '$lib/components/ui/label'
  import * as m from '$lib/paraglide/messages'

  interface User {
    id: string
    name: string
    email: string
    role: string
    teamName: string | null
    isActive: boolean
  }

  interface Props {
    value: string
    disabled?: boolean
  }

  let { value = $bindable(''), disabled = false }: Props = $props()

  let search = $state('')
  let users = $state<User[]>([])
  let open = $state(false)
  let loading = $state(false)
  let fallback = $state(false)
  let selectedName = $state('')
  let debounceTimer = $state<ReturnType<typeof setTimeout> | null>(null)

  // Track the input element and dropdown for click-outside handling
  let containerRef = $state<HTMLDivElement | null>(null)

  async function fetchUsers(query: string) {
    loading = true
    try {
      const result = await api.api.v1.users.get({
        query: { search: query, limit: 20, isActive: 'true' },
      })

      if (result.error) {
        const status = (result.error as any)?.status
        if (status === 403 || status === 401) {
          // User doesn't have admin/hr role -- fall back to manual ID input
          fallback = true
          return
        }
        users = []
        return
      }

      users = (result.data as any)?.data ?? []
    } catch {
      users = []
    } finally {
      loading = false
    }
  }

  function handleInput(e: Event) {
    const target = e.target as HTMLInputElement
    search = target.value
    open = true

    // Clear any previously selected value when user edits the search
    if (selectedName && search !== selectedName) {
      value = ''
      selectedName = ''
    }

    if (debounceTimer) clearTimeout(debounceTimer)
    debounceTimer = setTimeout(() => {
      fetchUsers(search)
    }, 300)
  }

  function selectUser(user: User) {
    value = user.id
    selectedName = user.name
    search = `${user.name} (${user.email})`
    open = false
  }

  function handleFocus() {
    if (!fallback) {
      open = true
      if (users.length === 0 && !loading) {
        fetchUsers(search)
      }
    }
  }

  function handleClickOutside(e: MouseEvent) {
    if (containerRef && !containerRef.contains(e.target as Node)) {
      open = false
    }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      open = false
    }
  }

  $effect(() => {
    document.addEventListener('mousedown', handleClickOutside)
    document.addEventListener('keydown', handleKeydown)
    return () => {
      document.removeEventListener('mousedown', handleClickOutside)
      document.removeEventListener('keydown', handleKeydown)
    }
  })

  // Initial fetch on mount to check access
  $effect(() => {
    fetchUsers('')
  })
</script>

<div class="space-y-1.5">
  <Label for="userId">{m.form_staff_name()}</Label>

  {#if fallback}
    <!-- Fallback: manual UUID input for non-admin/hr users -->
    <Input
      id="userId"
      type="text"
      placeholder={m.form_staff_name()}
      bind:value={value}
      required
      {disabled}
    />
    <p class="text-xs text-muted-foreground">
      {m.form_error_select_employee()}
    </p>
  {:else}
    <!-- Searchable employee selector for admin/hr users -->
    <div bind:this={containerRef} class="relative">
      <Input
        id="userId"
        type="text"
        placeholder={m.users_search_placeholder()}
        value={search}
        oninput={handleInput}
        onfocus={handleFocus}
        autocomplete="off"
        required={!value}
        {disabled}
      />

      {#if value}
        <input type="hidden" name="userId" value={value} />
      {/if}

      {#if open && !disabled}
        <div
          class="absolute z-50 mt-1 max-h-60 w-full overflow-auto rounded-lg border bg-popover p-1 shadow-md"
        >
          {#if loading}
            <div class="px-3 py-2 text-sm text-muted-foreground">
              {m.common_loading()}
            </div>
          {:else if users.length === 0}
            <div class="px-3 py-2 text-sm text-muted-foreground">
              {search ? m.users_empty() : m.users_search_placeholder()}
            </div>
          {:else}
            {#each users as user (user.id)}
              <button
                type="button"
                class="flex w-full flex-col items-start rounded-md px-3 py-2 text-left text-sm hover:bg-accent hover:text-accent-foreground {user.id === value ? 'bg-accent' : ''}"
                onclick={() => selectUser(user)}
              >
                <span class="font-medium">{user.name}</span>
                <span class="text-xs text-muted-foreground">
                  {user.email}
                  {#if user.teamName}
                    &middot; {user.teamName}
                  {/if}
                </span>
              </button>
            {/each}
          {/if}
        </div>
      {/if}
    </div>
  {/if}
</div>

// src/components/points/employee-selector.tsx
import { useState, useEffect, useRef } from 'react'
import { Search, User } from 'lucide-react'
import { Input } from '~/components/ui/input'
import { cn } from '~/lib/utils'

type Employee = {
  readonly id: string
  readonly name: string
  readonly email: string
  readonly role: string
  readonly avatarUrl: string | null
}

type EmployeeSelectorProps = {
  readonly employees: readonly Employee[]
  readonly value?: string
  readonly onChange: (id: string) => void
  readonly excludeId?: string
  readonly className?: string
}

export function EmployeeSelector({
  employees,
  value,
  onChange,
  excludeId,
  className,
}: EmployeeSelectorProps) {
  const [search, setSearch] = useState('')
  const [isOpen, setIsOpen] = useState(false)
  const containerRef = useRef<HTMLDivElement>(null)

  const selected = employees.find((e) => e.id === value)

  const filtered = employees.filter((e) => {
    if (e.id === excludeId) return false
    if (!search) return true
    const q = search.toLowerCase()
    return e.name.toLowerCase().includes(q) || e.email.toLowerCase().includes(q)
  })

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        setIsOpen(false)
      }
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  return (
    <div ref={containerRef} className={cn('relative', className)}>
      {selected && !isOpen ? (
        <button
          type="button"
          className="flex items-center gap-3 w-full rounded-lg border border-border bg-card p-3 text-left hover:bg-muted/50 transition-colors"
          onClick={() => {
            setIsOpen(true)
            setSearch('')
          }}
        >
          <div className="flex items-center justify-center h-8 w-8 rounded-full bg-primary/10">
            <User className="h-4 w-4 text-primary" />
          </div>
          <div>
            <p className="text-sm font-medium">{selected.name}</p>
            <p className="text-xs text-muted-foreground">{selected.email}</p>
          </div>
        </button>
      ) : (
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search employee by name..."
            value={search}
            onChange={(e) => {
              setSearch(e.target.value)
              setIsOpen(true)
            }}
            onFocus={() => setIsOpen(true)}
            className="pl-9"
          />
        </div>
      )}

      {isOpen && (
        <div className="absolute z-50 mt-1 w-full rounded-lg border border-border bg-card shadow-lg max-h-60 overflow-y-auto">
          {filtered.length === 0 ? (
            <p className="p-3 text-sm text-muted-foreground text-center">
              No employees found
            </p>
          ) : (
            filtered.map((emp) => (
              <button
                key={emp.id}
                type="button"
                className={cn(
                  'flex items-center gap-3 w-full p-3 text-left hover:bg-muted/50 transition-colors',
                  emp.id === value && 'bg-primary/5',
                )}
                onClick={() => {
                  onChange(emp.id)
                  setIsOpen(false)
                  setSearch('')
                }}
              >
                <div className="flex items-center justify-center h-8 w-8 rounded-full bg-primary/10 shrink-0">
                  <User className="h-4 w-4 text-primary" />
                </div>
                <div className="min-w-0">
                  <p className="text-sm font-medium truncate">{emp.name}</p>
                  <p className="text-xs text-muted-foreground truncate">{emp.email}</p>
                </div>
              </button>
            ))
          )}
        </div>
      )}
    </div>
  )
}
