// packages/web/src/lib/components/points/PointActions.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button'
  import ChallengeDialog from './ChallengeDialog.svelte'
  import AppealDialog from './AppealDialog.svelte'
  import { userState } from '$lib/state/userState.svelte'
  import * as m from '$lib/paraglide/messages'

  interface PointData {
    id: string
    userId?: string
    submitter?: { id?: string } | null
    status: string
    category?: { code?: string } | null
  }

  interface Props {
    point: PointData
  }

  let { point }: Props = $props()

  const user = $derived(userState.current)
  const isPenalti = $derived(point?.category?.code === 'PENALTI')
  const isActive = $derived(point?.status === 'active')
  const isRecipient = $derived(user?.id === point?.userId)
  const isSubmitter = $derived(user?.id === point?.submitter?.id)
  const isLeader = $derived(user?.role === 'leader')

  const canChallenge = $derived(isLeader && !isSubmitter && isPenalti && isActive)
  const canAppeal = $derived(isRecipient && isPenalti && isActive)

  let challengeOpen = $state(false)
  let appealOpen = $state(false)
</script>

{#if canChallenge || canAppeal}
  <div class="flex flex-col gap-2 w-full mt-4">
    {#if canChallenge}
      <Button
        class="w-full btn-gradient-purple rounded-xl py-6 text-base font-semibold shadow-lg shadow-purple-900/20"
        onclick={() => (challengeOpen = true)}
      >
        {m.point_action_challenge()}
      </Button>
      <ChallengeDialog pointId={point.id} bind:open={challengeOpen} />
    {/if}

    {#if canAppeal}
      <Button
        class="w-full btn-gradient-blue rounded-xl py-6 text-base font-semibold shadow-lg shadow-blue-900/20"
        onclick={() => (appealOpen = true)}
      >
        {m.point_action_appeal()}
      </Button>
      <AppealDialog pointId={point.id} bind:open={appealOpen} />
    {/if}
  </div>
{/if}

// src/components/points/point-actions.tsx
import * as React from 'react'
import { Button } from '~/components/ui/button'
import * as m from '~/paraglide/messages'
import { ChallengeDialog } from './challenge-dialog'
import { AppealDialog } from './appeal-dialog'
import { useSession } from '~/lib/auth-client'
import type { PointStatus, PointCategoryCode } from '~/shared/constants'

interface PointActionsProps {
  point: {
    id: string
    userId: string
    submittedBy: string
    status: string
    category: {
      code: string
    }
  }
}

export function PointActions({ point }: PointActionsProps) {
  const { data: session } = useSession()
  const user = session?.user

  if (!user) return null

  const isRecipient = user.id === point.userId
  const isSubmitter = user.id === point.submittedBy
  const isHRorAdmin = user.role === 'hr' || user.role === 'admin'
  const isLeader = user.role === 'leader'
  const isPenalti = point.category.code === 'PENALTI'
  const status = point.status as PointStatus

  const canChallenge = isLeader && !isSubmitter && isPenalti && status === 'active'
  const canAppeal = isRecipient && isPenalti && status === 'active'

  if (!canChallenge && !canAppeal) return null

  return (
    <div className="flex flex-col gap-2 w-full mt-4">
      {canChallenge && (
        <ChallengeDialog
          pointId={point.id}
          trigger={
            <Button className="w-full btn-gradient-purple rounded-xl py-6 text-base font-semibold shadow-lg shadow-purple-900/20">
              {m.point_action_challenge()}
            </Button>
          }
        />
      )}

      {canAppeal && (
        <AppealDialog
          pointId={point.id}
          trigger={
            <Button className="w-full btn-gradient-blue rounded-xl py-6 text-base font-semibold shadow-lg shadow-blue-900/20">
              {m.point_action_appeal()}
            </Button>
          }
        />
      )}
    </div>
  )
}
