// packages/web/src/routes/(authed)/admin/audit-log/+page.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button'
  import { Badge } from '$lib/components/ui/badge'
  import * as Table from '$lib/components/ui/table'
  import * as m from '$lib/paraglide/messages'
  import { Shield, Search, ChevronLeft, ChevronRight } from 'lucide-svelte'

  let { data } = $props()

  type AuditLog = {
    id: string
    createdAt: string
    action: string
    entityType: string | null
    entityId: string | null
    actorId: string | null
    actorName: string | null
  }

  let logs = $derived((data.logs ?? []) as AuditLog[])
  let meta = $derived(data.meta ?? { total: 0, page: 1, limit: 50 })
  let isLoading = $state(false)

  // Filter state
  let actionGroup = $state('')
  let entityType = $state('')
  let startDate = $state('')
  let endDate = $state('')
  let actor = $state('')
  let currentPage = $derived(data.meta?.page ?? 1)
  const totalPages = $derived(Math.ceil(meta.total / (meta.limit ?? 50)))

  const ACTION_GROUPS = [
    { value: '', label: () => m.audit_group_all() },
    { value: 'POINT_', label: () => m.audit_group_points() },
    { value: 'CHALLENGE_', label: () => m.audit_group_challenges() },
    { value: 'APPEAL_', label: () => m.audit_group_appeals() },
    { value: 'REDEMPTION_', label: () => m.audit_group_redemptions() },
    { value: 'USER_', label: () => m.audit_group_users() },
    { value: 'TEAM_', label: () => m.audit_group_teams() },
  ]

  function getActionBadgeClass(action: string): string {
    if (action.startsWith('POINT_SUBMITTED') || action.startsWith('POINT_APPROVED'))
      return 'bg-blue-100 text-blue-700 border-blue-200 dark:bg-blue-900/30 dark:text-blue-300'
    if (action.startsWith('POINT_REJECTED') || action.startsWith('POINT_REVOKED'))
      return 'bg-red-100 text-red-700 border-red-200 dark:bg-red-900/30 dark:text-red-300'
    if (action.startsWith('CHALLENGE_') || action.startsWith('APPEAL_'))
      return 'bg-purple-100 text-purple-700 border-purple-200 dark:bg-purple-900/30 dark:text-purple-300'
    if (action.startsWith('REDEMPTION_'))
      return 'bg-green-100 text-green-700 border-green-200 dark:bg-green-900/30 dark:text-green-300'
    if (action.startsWith('USER_') || action.startsWith('TEAM_'))
      return 'bg-gray-100 text-gray-700 border-gray-200 dark:bg-gray-800/50 dark:text-gray-300'
    return 'bg-gray-100 text-gray-600 border-gray-200 dark:bg-gray-800/50 dark:text-gray-400'
  }

  function formatTimestamp(iso: string) {
    const d = new Date(iso)
    return {
      date: d.toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }),
      time: d.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
    }
  }

  async function fetchLogs(opts?: { page?: number }) {
    isLoading = true
    const pg = opts?.page ?? currentPage
    try {
      const q = new URLSearchParams({ page: String(pg), limit: String(meta.limit ?? 50) })
      if (actionGroup) q.set('action', actionGroup)
      if (entityType) q.set('entityType', entityType)
      if (startDate) q.set('startDate', startDate)
      if (endDate) q.set('endDate', endDate)
      if (actor) q.set('actorId', actor)
      const res = await fetch(`/api/v1/audit-logs?${q.toString()}`, { credentials: 'include' })
      const json = await res.json()
      logs = (json.data ?? []) as AuditLog[]
      meta = json.meta ?? { total: 0, page: pg, limit: 50 }
      currentPage = pg
    } finally {
      isLoading = false
    }
  }

  function handleActionGroup(val: string) {
    actionGroup = val
    currentPage = 1
    fetchLogs({ page: 1 })
  }

  function handleSearch() {
    currentPage = 1
    fetchLogs({ page: 1 })
  }
</script>

<div class="mx-auto max-w-4xl space-y-6 p-4 pb-12">
  <!-- Header -->
  <div class="flex items-center gap-3">
    <div class="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10">
      <Shield class="h-5 w-5 text-foreground" />
    </div>
    <div>
      <h1 class="text-xl font-bold text-foreground">{m.audit_title()}</h1>
      <p class="text-xs text-muted-foreground">{m.audit_subtitle()}</p>
    </div>
  </div>

  <!-- Filter bar -->
  <div class="space-y-4 rounded-xl border border-border bg-card p-4 shadow-card">
    <!-- Action group pills -->
    <div class="flex flex-wrap gap-2">
      {#each ACTION_GROUPS as group (group.value)}
        <button
          type="button"
          onclick={() => handleActionGroup(group.value)}
          class="rounded-full border px-3 py-1 text-xs font-medium transition-colors {actionGroup ===
          group.value
            ? 'border-primary bg-primary text-primary-foreground'
            : 'border-border bg-primary/5 text-muted-foreground hover:border-primary/40 hover:bg-primary/10 hover:text-primary'}"
        >
          {group.label()}
        </button>
      {/each}
    </div>

    <!-- Secondary filters -->
    <div class="grid grid-cols-1 gap-3 sm:grid-cols-2 md:grid-cols-4">
      <div class="relative">
        <Search class="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground" />
        <input
          type="text"
          placeholder={m.audit_actor_placeholder()}
          bind:value={actor}
          class="h-9 w-full rounded-lg border border-border bg-background pl-8 pr-3 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
        />
      </div>
      <input
        type="text"
        placeholder={m.audit_entity_type_placeholder()}
        bind:value={entityType}
        class="h-9 rounded-lg border border-border bg-background px-3 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
      />
      <input
        type="date"
        bind:value={startDate}
        class="h-9 rounded-lg border border-border bg-background px-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
      />
      <input
        type="date"
        bind:value={endDate}
        class="h-9 rounded-lg border border-border bg-background px-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
      />
    </div>
    <div class="flex justify-end">
      <Button
        size="sm"
        onclick={handleSearch}
        disabled={isLoading}
        class="h-9 px-5 bg-primary hover:bg-primary/80 text-primary-foreground"
      >
        {isLoading ? m.common_loading() : m.audit_apply_filters()}
      </Button>
    </div>
  </div>

  <!-- Content -->
  {#if isLoading}
    <div class="space-y-2">
      {#each [0, 1, 2, 3, 4, 5] as _i}
        <div class="h-14 animate-pulse rounded-xl border border-border bg-muted/50"></div>
      {/each}
    </div>
  {:else if logs.length === 0}
    <div class="flex flex-col items-center justify-center py-16 text-center">
      <Shield class="mb-3 h-10 w-10 text-muted-foreground/30" />
      <p class="text-sm text-muted-foreground">{m.audit_empty()}</p>
    </div>
  {:else}
    <!-- Desktop table -->
    <div class="hidden overflow-hidden rounded-xl border border-border shadow-card md:block">
      <Table.Root>
        <Table.Header>
          <Table.Row class="bg-muted/60">
            <Table.Head class="w-36 text-xs font-semibold text-muted-foreground">{m.audit_col_timestamp()}</Table.Head>
            <Table.Head class="text-xs font-semibold text-muted-foreground">{m.audit_col_actor()}</Table.Head>
            <Table.Head class="text-xs font-semibold text-muted-foreground">{m.audit_col_action()}</Table.Head>
            <Table.Head class="text-xs font-semibold text-muted-foreground">{m.audit_col_entity_type()}</Table.Head>
            <Table.Head class="text-xs font-semibold text-muted-foreground">{m.audit_col_entity_id()}</Table.Head>
            <Table.Head class="text-xs font-semibold text-muted-foreground">{m.audit_col_details()}</Table.Head>
          </Table.Row>
        </Table.Header>
        <Table.Body>
          {#each logs as log (log.id)}
            {@const ts = formatTimestamp(log.createdAt)}
            <Table.Row class="transition-colors hover:bg-muted/30">
              <Table.Cell class="text-xs">
                <span class="block font-medium text-foreground">{ts.date}</span>
                <span class="block text-muted-foreground">{ts.time}</span>
              </Table.Cell>
              <Table.Cell>
                <span class="text-xs font-medium text-foreground">
                  {log.actorName ?? log.actorId ?? '—'}
                </span>
              </Table.Cell>
              <Table.Cell>
                <Badge
                  variant="outline"
                  class="font-mono text-[10px] px-2 py-0.5 {getActionBadgeClass(log.action)}"
                >
                  {log.action}
                </Badge>
              </Table.Cell>
              <Table.Cell class="text-xs text-muted-foreground">{log.entityType ?? '—'}</Table.Cell>
              <Table.Cell class="max-w-[100px] truncate font-mono text-xs text-muted-foreground">
                {log.entityId ?? '—'}
              </Table.Cell>
              <Table.Cell class="text-xs text-muted-foreground">—</Table.Cell>
            </Table.Row>
          {/each}
        </Table.Body>
      </Table.Root>
    </div>

    <!-- Mobile cards -->
    <div class="space-y-3 md:hidden">
      {#each logs as log (log.id)}
        {@const ts = formatTimestamp(log.createdAt)}
        <div class="space-y-3 rounded-xl border border-border bg-card p-4">
          <div class="flex items-start justify-between gap-2">
            <Badge
              variant="outline"
              class="shrink-0 font-mono text-[10px] px-2 py-0.5 {getActionBadgeClass(log.action)}"
            >
              {log.action}
            </Badge>
            <span class="text-right text-[10px] text-muted-foreground">{ts.date} {ts.time}</span>
          </div>
          <div class="grid grid-cols-2 gap-2 text-xs">
            <div>
              <p class="mb-0.5 text-muted-foreground">{m.audit_col_actor()}</p>
              <p class="font-medium text-foreground">{log.actorName ?? log.actorId ?? '—'}</p>
            </div>
            <div>
              <p class="mb-0.5 text-muted-foreground">{m.audit_entity_label()}</p>
              <p class="font-medium text-foreground">{log.entityType ?? '—'}</p>
              <p class="truncate font-mono text-[10px] text-muted-foreground">
                {log.entityId ?? '—'}
              </p>
            </div>
          </div>
        </div>
      {/each}
    </div>

    <!-- Pagination -->
    <div class="flex items-center justify-between pt-2">
      <p class="text-xs text-muted-foreground">
        {m.common_page_of({ page: String(currentPage), total: String(totalPages) })} ·
        {m.audit_total({ total: String(meta.total) })}
      </p>
      <div class="flex items-center gap-2">
        <Button
          variant="outline"
          size="sm"
          disabled={currentPage <= 1 || isLoading}
          onclick={() => fetchLogs({ page: currentPage - 1 })}
          class="h-8 px-3"
        >
          <ChevronLeft class="mr-1 h-3.5 w-3.5" />
          {m.common_previous()}
        </Button>
        <Button
          variant="outline"
          size="sm"
          disabled={currentPage >= totalPages || isLoading}
          onclick={() => fetchLogs({ page: currentPage + 1 })}
          class="h-8 px-3"
        >
          {m.common_next()}
          <ChevronRight class="ml-1 h-3.5 w-3.5" />
        </Button>
      </div>
    </div>
  {/if}
</div>

// src/routes/_authed/admin/audit-log.tsx
import { useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import * as m from '~/paraglide/messages'
import { Shield, ChevronLeft, ChevronRight, Search } from 'lucide-react'
import { Badge } from '~/components/ui/badge'
import { Button } from '~/components/ui/button'
import { Input } from '~/components/ui/input'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '~/components/ui/table'
import { listAuditLogsFn } from '~/server/functions/audit-logs'

type AuditLog = {
  id: string
  createdAt: string
  action: string
  entityType: string | null
  entityId: string | null
  actorId: string | null
  actorName: string | null
  actorRole: string | null
  details: Record<string, unknown> | null
}

type Meta = {
  total: number
  page: number
  limit: number
  totalPages: number
}

const ACTION_GROUP_VALUES = ['', 'POINT_', 'CHALLENGE_', 'APPEAL_', 'REDEMPTION_', 'USER_', 'TEAM_'] as const

function getActionBadgeClass(action: string): string {
  if (action.startsWith('POINT_SUBMITTED') || action.startsWith('POINT_APPROVED')) {
    return 'bg-blue-100 text-blue-700 border-blue-200'
  }
  if (action.startsWith('POINT_REJECTED') || action.startsWith('POINT_REVOKED')) {
    return 'bg-red-100 text-red-700 border-red-200'
  }
  if (action.startsWith('CHALLENGE_') || action.startsWith('APPEAL_')) {
    return 'bg-purple-100 text-purple-700 border-purple-200'
  }
  if (action.startsWith('REDEMPTION_')) {
    return 'bg-green-100 text-green-700 border-green-200'
  }
  if (action.startsWith('USER_') || action.startsWith('TEAM_')) {
    return 'bg-gray-100 text-gray-700 border-gray-200'
  }
  return 'bg-gray-100 text-gray-600 border-gray-200'
}

function getRoleBadgeClass(role: string | null): string {
  if (role === 'admin') return 'bg-primary/10 text-primary border-primary/20'
  if (role === 'hr') return 'bg-primary/10 text-primary border-primary/20'
  return 'bg-gray-100 text-gray-600 border-gray-200'
}

function formatTimestamp(iso: string): { date: string; time: string } {
  const d = new Date(iso)
  return {
    date: d.toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }),
    time: d.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }),
  }
}

function DetailsCell({ details }: { details: Record<string, unknown> | null }) {
  const [open, setOpen] = useState(false)
  if (!details || Object.keys(details).length === 0) return <span className="text-muted-foreground text-xs">—</span>
  return (
    <div>
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="text-xs text-primary underline underline-offset-2 hover:text-primary/70 transition-colors"
      >
        {open ? m.audit_hide() : m.audit_show()}
      </button>
      {open && (
        <pre className="mt-1 max-w-xs overflow-auto rounded bg-muted px-2 py-1 text-[10px] leading-relaxed text-muted-foreground whitespace-pre-wrap break-all">
          {JSON.stringify(details, null, 2)}
        </pre>
      )}
    </div>
  )
}

export const Route = createFileRoute('/_authed/admin/audit-log')({
  loader: async () => {
    const result = await listAuditLogsFn({ data: { page: 1, limit: 50 } })
    return result
  },
  component: AuditLogPage,
  pendingComponent: AuditLogSkeleton,
})

function AuditLogSkeleton() {
  return (
    <div className="max-w-4xl mx-auto p-4 space-y-6 animate-pulse">
      <div className="flex items-center gap-3">
        <div className="h-9 w-9 rounded-xl bg-muted" />
        <div className="space-y-1">
          <div className="h-5 w-24 rounded bg-muted" />
          <div className="h-3 w-44 rounded bg-muted" />
        </div>
      </div>
      <div className="h-32 rounded-xl border border-border bg-card" />
      <div className="space-y-2">
        {Array.from({ length: 6 }).map((_, i) => (
          <div key={i} className="h-14 rounded-xl border border-border bg-card" />
        ))}
      </div>
    </div>
  )
}

function AuditLogPage() {
  const initialData = Route.useLoaderData()
  const { session } = Route.useRouteContext()

  const role = session?.appUser?.role ?? 'employee'

  const [logs, setLogs] = useState<AuditLog[]>((initialData.logs ?? []) as AuditLog[])
  const [meta, setMeta] = useState<Meta>((initialData.meta ?? { total: 0, page: 1, limit: 50, totalPages: 1 }) as Meta)
  const [isLoading, setIsLoading] = useState(false)

  // Filter state
  const [actionGroup, setActionGroup] = useState('')
  const [entityType, setEntityType] = useState('')
  const [startDate, setStartDate] = useState('')
  const [endDate, setEndDate] = useState('')
  const [actor, setActor] = useState('')
  const [page, setPage] = useState(1)

  if (role !== 'hr' && role !== 'admin') {
    return (
      <div className="flex flex-col items-center justify-center py-24 text-center px-4">
        <Shield className="h-12 w-12 text-muted-foreground/40 mb-3" />
        <h2 className="text-lg font-semibold text-foreground">{m.common_access_denied()}</h2>
        <p className="text-sm text-muted-foreground mt-1">{m.common_no_permission()}</p>
      </div>
    )
  }

  async function fetchLogs(opts?: {
    actionGroup?: string
    entityType?: string
    startDate?: string
    endDate?: string
    actor?: string
    page?: number
  }) {
    const ag = opts?.actionGroup ?? actionGroup
    const et = opts?.entityType ?? entityType
    const sd = opts?.startDate ?? startDate
    const ed = opts?.endDate ?? endDate
    const ac = opts?.actor ?? actor
    const pg = opts?.page ?? page

    setIsLoading(true)
    try {
      const result = await listAuditLogsFn({
        data: {
          page: pg,
          limit: 50,
          action: ag || undefined,
          entityType: et || undefined,
          startDate: sd || undefined,
          endDate: ed || undefined,
          actorId: ac || undefined,
        },
      })
      setLogs((result.logs ?? []) as AuditLog[])
      setMeta((result.meta ?? { total: 0, page: pg, limit: 50, totalPages: 1 }) as Meta)
    } finally {
      setIsLoading(false)
    }
  }

  function handleActionGroup(val: string) {
    setActionGroup(val)
    setPage(1)
    fetchLogs({ actionGroup: val, page: 1 })
  }

  function handleSearch() {
    setPage(1)
    fetchLogs({ page: 1 })
  }

  function handlePageChange(newPage: number) {
    setPage(newPage)
    fetchLogs({ page: newPage })
  }

  return (
    <div className="max-w-4xl mx-auto p-4 space-y-6 pb-12">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10">
          <Shield className="h-5 w-5 text-foreground" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-foreground">{m.audit_title()}</h1>
          <p className="text-xs text-muted-foreground">{m.audit_subtitle()}</p>
        </div>
      </div>

      {/* Filter bar */}
      <div className="rounded-xl border border-border bg-card shadow-card p-4 space-y-4">
        {/* Action group pills */}
        <div className="flex flex-wrap gap-2">
          {ACTION_GROUP_VALUES.map((val) => {
            const label = val === '' ? m.audit_group_all()
              : val === 'POINT_' ? m.audit_group_points()
              : val === 'CHALLENGE_' ? m.audit_group_challenges()
              : val === 'APPEAL_' ? m.audit_group_appeals()
              : val === 'REDEMPTION_' ? m.audit_group_redemptions()
              : val === 'USER_' ? m.audit_group_users()
              : m.audit_group_teams()
            return (
              <button
                key={val}
                type="button"
                onClick={() => handleActionGroup(val)}
                className={`rounded-full px-3 py-1 text-xs font-medium transition-colors border ${
                  actionGroup === val
                    ? 'bg-primary text-primary-foreground border-primary'
                    : 'bg-primary/5 text-muted-foreground border-border hover:border-primary/40 hover:text-primary hover:bg-primary/10'
                }`}
              >
                {label}
              </button>
            )
          })}
        </div>

        {/* Secondary filters */}
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 md:grid-cols-4">
          <div className="relative">
            <Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground" />
            <Input
              placeholder={m.audit_actor_placeholder()}
              value={actor}
              onChange={(e) => setActor(e.target.value)}
              className="h-9 pl-8 text-sm"
            />
          </div>
          <Input
            placeholder={m.audit_entity_type_placeholder()}
            value={entityType}
            onChange={(e) => setEntityType(e.target.value)}
            className="h-9 text-sm"
          />
          <Input
            type="date"
            value={startDate}
            onChange={(e) => setStartDate(e.target.value)}
            className="h-9 text-sm"
            title="Start date"
          />
          <Input
            type="date"
            value={endDate}
            onChange={(e) => setEndDate(e.target.value)}
            className="h-9 text-sm"
            title="End date"
          />
        </div>

        <div className="flex justify-end">
          <Button
            size="sm"
            onClick={handleSearch}
            disabled={isLoading}
            className="bg-primary hover:bg-primary/80 text-primary-foreground h-9 px-5"
          >
            {isLoading ? m.common_loading() : m.audit_apply_filters()}
          </Button>
        </div>
      </div>

      {/* Table — desktop */}
      {isLoading ? (
        <div className="space-y-2">
          {Array.from({ length: 6 }).map((_, i) => (
            <div key={i} className="h-14 rounded-xl border border-border bg-muted/50 animate-pulse" />
          ))}
        </div>
      ) : logs.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 text-center">
          <Shield className="h-10 w-10 text-muted-foreground/30 mb-3" />
          <p className="text-muted-foreground text-sm">{m.audit_empty()}</p>
        </div>
      ) : (
        <>
          {/* Desktop table */}
          <div className="hidden md:block rounded-xl border border-border shadow-card overflow-hidden">
            <Table>
              <TableHeader>
                <TableRow className="bg-muted/60">
                  <TableHead className="text-xs font-semibold text-muted-foreground w-36">{m.audit_col_timestamp()}</TableHead>
                  <TableHead className="text-xs font-semibold text-muted-foreground">{m.audit_col_actor()}</TableHead>
                  <TableHead className="text-xs font-semibold text-muted-foreground">{m.audit_col_action()}</TableHead>
                  <TableHead className="text-xs font-semibold text-muted-foreground">{m.audit_col_entity_type()}</TableHead>
                  <TableHead className="text-xs font-semibold text-muted-foreground">{m.audit_col_entity_id()}</TableHead>
                  <TableHead className="text-xs font-semibold text-muted-foreground">{m.audit_col_details()}</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {logs.map((log) => {
                  const { date, time } = formatTimestamp(log.createdAt)
                  return (
                    <TableRow key={log.id} className="hover:bg-muted/30 transition-colors">
                      <TableCell className="text-xs">
                        <span className="block text-foreground font-medium">{date}</span>
                        <span className="block text-muted-foreground">{time}</span>
                      </TableCell>
                      <TableCell>
                        <div className="flex flex-col gap-1">
                          <span className="text-xs font-medium text-foreground">
                            {log.actorName ?? log.actorId ?? '—'}
                          </span>
                          {log.actorRole && (
                            <Badge
                              variant="outline"
                              className={`text-[10px] px-1.5 py-0 w-fit ${getRoleBadgeClass(log.actorRole)}`}
                            >
                              {log.actorRole}
                            </Badge>
                          )}
                        </div>
                      </TableCell>
                      <TableCell>
                        <Badge
                          variant="outline"
                          className={`text-[10px] px-2 py-0.5 font-mono ${getActionBadgeClass(log.action)}`}
                        >
                          {log.action}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-xs text-muted-foreground">
                        {log.entityType ?? '—'}
                      </TableCell>
                      <TableCell className="text-xs font-mono text-muted-foreground max-w-[100px] truncate">
                        {log.entityId ?? '—'}
                      </TableCell>
                      <TableCell>
                        <DetailsCell details={log.details} />
                      </TableCell>
                    </TableRow>
                  )
                })}
              </TableBody>
            </Table>
          </div>

          {/* Mobile card layout */}
          <div className="md:hidden space-y-3">
            {logs.map((log) => {
              const { date, time } = formatTimestamp(log.createdAt)
              return (
                <div key={log.id} className="rounded-xl border border-border bg-card p-4 space-y-3">
                  <div className="flex items-start justify-between gap-2">
                    <Badge
                      variant="outline"
                      className={`text-[10px] px-2 py-0.5 font-mono shrink-0 ${getActionBadgeClass(log.action)}`}
                    >
                      {log.action}
                    </Badge>
                    <span className="text-[10px] text-muted-foreground text-right">
                      {date} {time}
                    </span>
                  </div>

                  <div className="grid grid-cols-2 gap-2 text-xs">
                    <div>
                      <p className="text-muted-foreground mb-0.5">{m.audit_col_actor()}</p>
                      <p className="font-medium text-foreground">{log.actorName ?? log.actorId ?? '—'}</p>
                      {log.actorRole && (
                        <Badge
                          variant="outline"
                          className={`text-[10px] px-1.5 py-0 mt-1 ${getRoleBadgeClass(log.actorRole)}`}
                        >
                          {log.actorRole}
                        </Badge>
                      )}
                    </div>
                    <div>
                      <p className="text-muted-foreground mb-0.5">{m.audit_entity_label()}</p>
                      <p className="font-medium text-foreground">{log.entityType ?? '—'}</p>
                      <p className="font-mono text-muted-foreground text-[10px] truncate">{log.entityId ?? '—'}</p>
                    </div>
                  </div>

                  <DetailsCell details={log.details} />
                </div>
              )
            })}
          </div>

          {/* Pagination */}
          <div className="flex items-center justify-between pt-2">
            <p className="text-xs text-muted-foreground">
              {m.common_page_of({ page: String(meta.page), total: String(meta.totalPages) })} &middot; {m.audit_total({ total: String(meta.total) })}
            </p>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                disabled={page <= 1 || isLoading}
                onClick={() => handlePageChange(page - 1)}
                className="h-8 px-3"
              >
                <ChevronLeft className="h-3.5 w-3.5 mr-1" />
                {m.common_previous()}
              </Button>
              <Button
                variant="outline"
                size="sm"
                disabled={page >= meta.totalPages || isLoading}
                onClick={() => handlePageChange(page + 1)}
                className="h-8 px-3"
              >
                {m.common_next()}
                <ChevronRight className="h-3.5 w-3.5 ml-1" />
              </Button>
            </div>
          </div>
        </>
      )}
    </div>
  )
}
