// src/components/points/challenge-dialog.tsx
import * as React from 'react'
import * as m from '~/paraglide/messages'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '~/components/ui/dialog'
import { Button } from '~/components/ui/button'
import { Textarea } from '~/components/ui/textarea'
import { Label } from '~/components/ui/label'
import { toast } from 'sonner'
import { fileChallengeFn } from '~/server/functions/challenges'
import { useRouter } from '@tanstack/react-router'

interface ChallengeDialogProps {
  pointId: string
  trigger?: React.ReactElement
}

export function ChallengeDialog({ pointId, trigger }: ChallengeDialogProps) {
  const [open, setOpen] = React.useState(false)
  const [reason, setReason] = React.useState('')
  const [isSubmitting, setIsSubmitting] = React.useState(false)
  const router = useRouter()

  async function onSubmit() {
    if (!reason.trim()) return

    setIsSubmitting(true)
    try {
      await fileChallengeFn({ data: { pointId, reason } })
      toast.success(m.challenge_success())
      setOpen(false)
      setReason('')
      router.invalidate()
    } catch (error) {
      toast.error(error instanceof Error ? error.message : m.challenge_failed())
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger render={trigger ?? <Button variant="outline" className="text-[#6D50B8] border-[#6D50B8] hover:bg-purple-50 dark:hover:bg-purple-900/20">Challenge</Button>} />
      <DialogContent className="sm:max-w-[425px] rounded-[20px]">
        <DialogHeader>
          <DialogTitle>{m.challenge_title()}</DialogTitle>
          <DialogDescription>
            {m.challenge_description()}
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid gap-2">
            <Label htmlFor="reason">{m.challenge_reason_label()}</Label>
            <Textarea
              id="reason"
              placeholder={m.challenge_reason_placeholder()}
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              className="min-h-[120px] rounded-xl"
            />
          </div>
          <div className="p-3 rounded-lg bg-blue-50 border border-blue-100 dark:bg-blue-900/20 dark:border-blue-800/50">
            <p className="text-xs text-blue-700 dark:text-blue-300 leading-relaxed">
              <strong>Note:</strong> {m.challenge_note()}
            </p>
          </div>
        </div>
        <DialogFooter>
          <Button
            type="submit"
            onClick={onSubmit}
            disabled={isSubmitting || !reason.trim()}
            className="w-full bg-primary hover:bg-primary/80 rounded-xl"
          >
            {isSubmitting ? m.common_submitting() : m.challenge_submit()}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// packages/web/src/lib/components/points/ChallengeDialog.svelte
<script lang="ts">
  import { invalidateAll } from '$app/navigation'
  import { toast } from 'svelte-sonner'
  import { api } from '$lib/api/client'
  import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter, Button, Label, Textarea } from '@coms-portal/ui/primitives'
  import * as m from '$lib/paraglide/messages'
  import { getErrorMessage } from '$lib/api/client'

  interface Props {
    pointId: string
    open?: boolean
    onClose?: () => void
  }

  let { pointId, open = $bindable(false), onClose }: Props = $props()

  let reason = $state('')
  let isSubmitting = $state(false)

  async function onSubmit(e: SubmitEvent) {
    e.preventDefault()
    if (!reason.trim()) return

    isSubmitting = true
    try {
      const result = await api.api.v1.points({ id: pointId }).challenges.post({ reason: reason.trim() })
      if (result.error) {
        toast.error(getErrorMessage(result.error, m.challenge_failed()))
        return
      }
      toast.success(m.challenge_success())
      open = false
      reason = ''
      onClose?.()
      await invalidateAll()
    } catch (err) {
      toast.error(err instanceof Error ? err.message : m.challenge_failed())
    } finally {
      isSubmitting = false
    }
  }
</script>

<Dialog bind:open>
  <DialogContent class="sm:max-w-[425px] rounded-[20px]">
    <DialogHeader>
      <DialogTitle>{m.challenge_title()}</DialogTitle>
      <DialogDescription>{m.challenge_description()}</DialogDescription>
    </DialogHeader>
    <form onsubmit={onSubmit} class="grid gap-4 py-4">
      <div class="grid gap-2">
        <Label for="challenge-reason">{m.challenge_reason_label()}</Label>
        <Textarea
          id="challenge-reason"
          placeholder={m.challenge_reason_placeholder()}
          bind:value={reason}
          class="min-h-[120px] rounded-xl"
          disabled={isSubmitting}
        />
      </div>
      <div class="p-3 rounded-lg bg-primary/10 border border-primary/15 dark:bg-primary/10 dark:border-primary/20">
        <p class="text-xs text-primary leading-relaxed">
          <strong>Note:</strong> {m.challenge_note()}
        </p>
      </div>
      <DialogFooter>
        <Button
          type="button"
          variant="outline"
          onclick={() => { open = false; onClose?.() }}
        >
          {m.common_cancel()}
        </Button>
        <Button
          type="submit"
          disabled={isSubmitting || !reason.trim()}
          class="bg-primary hover:bg-primary/80 rounded-xl"
        >
          {#if isSubmitting}{m.common_submitting()}{:else}{m.challenge_submit()}{/if}
        </Button>
      </DialogFooter>
    </form>
  </DialogContent>
</Dialog>
