// src/components/points/comment-thread.tsx
import * as React from 'react'
import { Button } from '~/components/ui/button'
import { Textarea } from '~/components/ui/textarea'
import { useSession } from '~/lib/auth-client'
import { listCommentsFn, createCommentFn } from '~/server/functions/comments'
import { useSuspenseQuery } from '@tanstack/react-query'
import { useRouter } from '@tanstack/react-router'
import { toast } from 'sonner'
import { Send, User as UserIcon } from 'lucide-react'

interface CommentThreadProps {
  entityId: string
  entityType: 'achievement' | 'challenge' | 'appeal'
}

export function CommentThread({ entityId, entityType }: CommentThreadProps) {
  const { data: session } = useSession()
  const [body, setBody] = React.useState('')
  const [isSubmitting, setIsSubmitting] = React.useState(false)
  const router = useRouter()

  const { data } = useSuspenseQuery({
    queryKey: ['comments', entityType, entityId],
    queryFn: () => listCommentsFn({ data: { entityType, entityId } }),
  })

  const comments = data?.comments ?? []

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!body.trim() || isSubmitting) return

    setIsSubmitting(true)
    try {
      await createCommentFn({ data: { entityType, entityId, body } })
      setBody('')
      router.invalidate()
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to post comment')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="space-y-6 pt-4">
      <h3 className="text-sm font-semibold text-foreground flex items-center gap-2">
        <span className="w-1.5 h-1.5 rounded-full bg-primary" />
        Comments ({comments.length})
      </h3>

      <div className="space-y-5">
        {comments.length === 0 ? (
          <p className="text-xs text-muted-foreground text-center py-4">No comments yet. Start the conversation!</p>
        ) : (
          comments.map((comment: any) => (
            <div key={comment.id} className="flex gap-3">
              <div className="h-8 w-8 rounded-full bg-muted flex items-center justify-center shrink-0">
                {comment.user?.avatarUrl ? (
                  <img src={comment.user.avatarUrl} alt="" className="h-full w-full rounded-full object-cover" />
                ) : (
                  <UserIcon className="h-4 w-4 text-muted-foreground" />
                )}
              </div>
              <div className="flex-1 space-y-1">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-foreground">{comment.user?.name ?? 'Unknown'}</span>
                  <span className="text-[10px] text-muted-foreground">
                    {new Date(comment.createdAt).toLocaleDateString('id-ID', {
                      day: 'numeric',
                      month: 'short',
                      hour: '2-digit',
                      minute: '2-digit'
                    })}
                  </span>
                </div>
                <div className="text-sm text-foreground leading-relaxed">
                  {comment.body}
                </div>
              </div>
            </div>
          ))
        )}
      </div>

      <form onSubmit={onSubmit} className="relative mt-4">
        <Textarea
          placeholder="Write a comment..."
          value={body}
          onChange={(e) => setBody(e.target.value)}
          className="pr-12 min-h-[100px] rounded-2xl bg-muted/30 border-none focus-visible:ring-1 focus-visible:ring-primary transition-all"
        />
        <Button
          type="submit"
          size="icon"
          disabled={!body.trim() || isSubmitting}
          className="absolute right-2 bottom-2 h-8 w-8 rounded-xl bg-primary hover:bg-primary/80 shadow-md shadow-primary/10"
        >
          <Send className="h-4 w-4" />
        </Button>
      </form>
    </div>
  )
}

// packages/web/src/lib/components/points/CommentThread.svelte
<script lang="ts">
  import { toast } from 'svelte-sonner'
  import { api } from '$lib/api/client'
  import { Textarea } from '$lib/components/ui/textarea'
  import { Button } from '$lib/components/ui/button'
  import { Send, User as UserIcon } from 'lucide-svelte'

  interface Comment {
    id: string
    body: string
    createdAt: string
    user?: { name?: string; avatarUrl?: string | null } | null
  }

  interface Props {
    entityId: string
    entityType: 'achievement' | 'challenge' | 'appeal'
    comments?: Comment[]
  }

  let { entityId, entityType, comments = [] }: Props = $props()

  let localComments = $state<Comment[]>(comments)
  let body = $state('')
  let isSubmitting = $state(false)

  async function onSubmit(e: SubmitEvent) {
    e.preventDefault()
    if (!body.trim() || isSubmitting) return

    isSubmitting = true
    try {
      const result = await api.api.v1.comments.post({ entityType, entityId, body: body.trim() })
      if (result.error) {
        const msg = (result.error as any)?.value?.error?.message ?? 'Failed to post comment'
        toast.error(msg)
        return
      }
      if (result.data) {
        localComments = [...localComments, result.data as Comment]
      }
      body = ''
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed to post comment')
    } finally {
      isSubmitting = false
    }
  }
</script>

<div class="space-y-6 pt-4">
  <h3 class="text-sm font-semibold text-foreground flex items-center gap-2">
    <span class="w-1.5 h-1.5 rounded-full bg-primary"></span>
    Comments ({localComments.length})
  </h3>

  <div class="space-y-5">
    {#if localComments.length === 0}
      <p class="text-xs text-muted-foreground text-center py-4">
        No comments yet. Start the conversation!
      </p>
    {:else}
      {#each localComments as comment (comment.id)}
        <div class="flex gap-3">
          <div class="h-8 w-8 rounded-full bg-muted flex items-center justify-center shrink-0">
            {#if comment.user?.avatarUrl}
              <img src={comment.user.avatarUrl} alt="" class="h-full w-full rounded-full object-cover" />
            {:else}
              <UserIcon class="h-4 w-4 text-muted-foreground" />
            {/if}
          </div>
          <div class="flex-1 space-y-1">
            <div class="flex items-center justify-between">
              <span class="text-xs font-bold text-foreground">{comment.user?.name ?? 'Unknown'}</span>
              <span class="text-[10px] text-muted-foreground">
                {new Date(comment.createdAt).toLocaleDateString('id-ID', {
                  day: 'numeric',
                  month: 'short',
                  hour: '2-digit',
                  minute: '2-digit',
                })}
              </span>
            </div>
            <div class="text-sm text-foreground leading-relaxed">{comment.body}</div>
          </div>
        </div>
      {/each}
    {/if}
  </div>

  <form onsubmit={onSubmit} class="relative mt-4">
    <Textarea
      placeholder="Write a comment..."
      bind:value={body}
      class="pr-12 min-h-[100px] rounded-2xl bg-muted/30 border-none focus-visible:ring-1 focus-visible:ring-primary transition-all"
    />
    <Button
      type="submit"
      size="icon"
      disabled={!body.trim() || isSubmitting}
      class="absolute right-2 bottom-2 h-8 w-8 rounded-xl bg-primary hover:bg-primary/80 shadow-md shadow-primary/10"
    >
      <Send class="h-4 w-4" />
    </Button>
  </form>
</div>
