// packages/web/src/routes/(authed)/notifications/+page.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button'
  import * as m from '$lib/paraglide/messages'
  import { goto } from '$app/navigation'
  import {
    Bell,
    Award,
    Clock,
    CheckCircle,
    XCircle,
    AlertCircle,
    ChevronLeft,
    ChevronRight,
  } from 'lucide-svelte'

  let { data } = $props()

  type NotificationRow = {
    id: string
    type: string
    title: string
    body: string | null
    entityType: string | null
    entityId: string | null
    isRead: boolean
    createdAt: string
  }

  let notifications = $derived((data.notifications.data ?? []) as NotificationRow[])
  let meta = $derived(data.notifications.meta ?? { total: 0, page: 1, limit: 50 })
  let page = $derived(data.notifications.meta?.page ?? 1)
  let isLoading = $state(false)

  const totalPages = $derived(Math.ceil((meta.total ?? 0) / (meta.limit ?? 50)))

  function formatRelativeTime(date: Date): string {
    const now = new Date()
    const diffMs = now.getTime() - date.getTime()
    const diffSec = Math.floor(diffMs / 1000)
    const diffMin = Math.floor(diffSec / 60)
    const diffHour = Math.floor(diffMin / 60)
    const diffDay = Math.floor(diffHour / 24)
    if (diffSec < 60) return m.time_just_now()
    if (diffMin < 60) return m.time_minutes_ago({ count: String(diffMin) })
    if (diffHour < 24) return m.time_hours_ago({ count: String(diffHour) })
    if (diffDay === 1) return m.time_yesterday()
    if (diffDay < 7) return m.time_days_ago({ count: String(diffDay) })
    return date.toLocaleDateString()
  }

  type LucideIcon = typeof Bell
  function iconForType(type: string): LucideIcon {
    switch (type) {
      case 'point_received':
      case 'point_approved':
        return CheckCircle
      case 'point_pending':
        return Clock
      case 'point_rejected':
        return XCircle
      case 'point_needs_approval':
        return AlertCircle
      case 'redemption_approved':
      case 'redemption_rejected':
        return Award
      default:
        return Bell
    }
  }

  function iconColorForType(type: string): string {
    switch (type) {
      case 'point_received':
      case 'point_approved':
        return 'text-emerald-500'
      case 'point_pending':
      case 'point_needs_approval':
        return 'text-[#F4C144]'
      case 'point_rejected':
        return 'text-destructive'
      default:
        return 'text-primary/50'
    }
  }

  async function loadPage(newPage: number) {
    isLoading = true
    try {
      const res = await fetch(`/api/v1/notifications?page=${newPage}&limit=20`, {
        credentials: 'include',
      })
      const json = await res.json()
      notifications = (json.data ?? []) as NotificationRow[]
      meta = json.meta
      page = newPage
    } finally {
      isLoading = false
    }
  }

  async function markAllRead() {
    await fetch('/api/v1/notifications/read-all', { method: 'PATCH', credentials: 'include' })
    notifications = notifications.map((n) => ({ ...n, isRead: true }))
  }

  async function handleItemClick(notif: NotificationRow) {
    if (!notif.isRead) {
      await fetch(`/api/v1/notifications/${notif.id}/read`, {
        method: 'PATCH',
        credentials: 'include',
      })
      notifications = notifications.map((n) => (n.id === notif.id ? { ...n, isRead: true } : n))
    }
    if (notif.entityType === 'achievement_points' && notif.entityId) {
      goto(`/points/${notif.entityId}`)
    }
  }
</script>

<div class="mx-auto max-w-3xl space-y-4 p-4">
  <!-- Page header -->
  <div class="flex items-center justify-between">
    <div class="flex items-center gap-3">
      <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/10">
        <Bell class="h-5 w-5 text-primary" />
      </div>
      <div>
        <h1 class="text-xl font-extrabold text-foreground">{m.nav_notifications()}</h1>
        <p class="text-xs font-medium text-muted-foreground">
          {meta.total}
          {m.nav_notifications().toLowerCase()}
        </p>
      </div>
    </div>
    <Button
      variant="outline"
      size="sm"
      class="min-h-[36px] rounded-xl border-border text-xs font-semibold text-primary transition-all duration-200 hover:border-primary/40 hover:bg-primary/8"
      onclick={markAllRead}
    >
      {m.notifications_mark_all_read()}
    </Button>
  </div>

  <div class="space-y-1">
    {#if isLoading}
      <div class="space-y-2">
        {#each [0, 1, 2, 3, 4] as _i (_i)}
          <div class="h-16 animate-pulse rounded-xl border border-border bg-primary/4"></div>
        {/each}
      </div>
    {:else if notifications.length === 0}
      <div
        class="flex flex-col items-center justify-center gap-3 rounded-2xl border border-border bg-card py-16 text-center shadow-card"
      >
        <div class="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/8">
          <Bell class="h-7 w-7 text-primary/40" />
        </div>
        <p class="font-semibold text-muted-foreground">{m.notifications_empty()}</p>
      </div>
    {:else}
      {#each notifications as notif (notif.id)}
        {@const Icon = iconForType(notif.type)}
        {@const iconColor = iconColorForType(notif.type)}
        <button
          type="button"
          class="block w-full text-left transition-colors"
          onclick={() => handleItemClick(notif)}
        >
          <div
            class="flex items-start gap-3 rounded-xl border px-4 py-3 transition-colors hover:bg-primary/4 {!notif.isRead
              ? 'border-primary/15 bg-primary/5'
              : 'border-border bg-card'}"
          >
            <div class="mt-0.5 shrink-0 {iconColor}">
              <Icon class="h-5 w-5" />
            </div>
            <div class="min-w-0 flex-1">
              <p class="text-sm font-medium leading-snug text-foreground">{notif.title}</p>
              {#if notif.body}
                <p class="mt-0.5 line-clamp-2 text-xs text-muted-foreground">{notif.body}</p>
              {/if}
              <p class="mt-1 text-xs text-muted-foreground">
                {formatRelativeTime(new Date(notif.createdAt))}
              </p>
            </div>
            {#if !notif.isRead}
              <div class="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-primary"></div>
            {/if}
          </div>
        </button>
      {/each}
    {/if}
  </div>

  {#if totalPages > 1}
    <div class="flex items-center justify-center gap-2 pt-2">
      <Button
        variant="outline"
        size="sm"
        disabled={page <= 1 || isLoading}
        onclick={() => loadPage(page - 1)}
        class="min-h-[36px] rounded-xl border-border hover:bg-primary/6 hover:text-primary"
      >
        <ChevronLeft class="h-4 w-4" />
        {m.common_previous()}
      </Button>
      <span
        class="rounded-xl border border-border bg-card px-3 py-1.5 text-sm font-semibold text-muted-foreground"
      >
        {m.common_page_of({ page: String(page), total: String(totalPages) })}
      </span>
      <Button
        variant="outline"
        size="sm"
        disabled={page >= totalPages || isLoading}
        onclick={() => loadPage(page + 1)}
        class="min-h-[36px] rounded-xl border-border hover:bg-primary/6 hover:text-primary"
      >
        {m.common_next()}
        <ChevronRight class="h-4 w-4" />
      </Button>
    </div>
  {/if}
</div>

// src/routes/_authed/notifications.tsx
import { useState } from 'react'
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import * as m from '~/paraglide/messages'
import {
  Award,
  Clock,
  CheckCircle,
  XCircle,
  AlertCircle,
  Bell,
} from 'lucide-react'
import { Button } from '~/components/ui/button'
import { cn } from '~/lib/utils'

type NotificationRow = {
  id: string
  userId: string
  branchId: string
  type: string
  title: string
  body: string | null
  entityType: string | null
  entityId: string | null
  isRead: boolean
  readAt: string | null
  createdAt: string
}

type PaginationMeta = {
  total: number
  page: number
  limit: number
}

type NotificationsResponse = {
  success: boolean
  data: NotificationRow[]
  meta: PaginationMeta
}

function formatRelativeTime(date: Date): string {
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffSec = Math.floor(diffMs / 1000)
  const diffMin = Math.floor(diffSec / 60)
  const diffHour = Math.floor(diffMin / 60)
  const diffDay = Math.floor(diffHour / 24)

  if (diffSec < 60) return m.time_just_now()
  if (diffMin < 60) return m.time_minutes_ago({ count: String(diffMin) })
  if (diffHour < 24) return m.time_hours_ago({ count: String(diffHour) })
  if (diffDay === 1) return m.time_yesterday()
  if (diffDay < 7) return m.time_days_ago({ count: String(diffDay) })
  return date.toLocaleDateString()
}

function NotificationIcon({ type }: { type: string }) {
  switch (type) {
    case 'point_received':
      return <Award className="h-5 w-5 text-emerald-500" />
    case 'point_pending':
      return <Clock className="h-5 w-5 text-[#F4C144]" />
    case 'point_approved':
      return <CheckCircle className="h-5 w-5 text-emerald-500" />
    case 'point_rejected':
      return <XCircle className="h-5 w-5 text-destructive" />
    case 'point_needs_approval':
      return <AlertCircle className="h-5 w-5 text-[#F4C144]" />
    default:
      return <Bell className="h-5 w-5 text-primary/50" />
  }
}

async function fetchNotifications(opts: {
  page: number
  limit: number
  unread?: boolean
}): Promise<NotificationsResponse> {
  const params = new URLSearchParams({
    page: String(opts.page),
    limit: String(opts.limit),
  })
  if (opts.unread !== undefined) {
    params.set('unread', String(opts.unread))
  }
  const res = await fetch(`/api/v1/notifications?${params.toString()}`, {
    credentials: 'include',
  })
  if (!res.ok) throw new Error('Failed to fetch notifications')
  return res.json() as Promise<NotificationsResponse>
}

async function markAllReadFn(): Promise<void> {
  const res = await fetch('/api/v1/notifications/read-all', {
    method: 'PATCH',
    credentials: 'include',
  })
  if (!res.ok) throw new Error('Failed to mark all as read')
}

async function markOneFn(id: string): Promise<void> {
  const res = await fetch(`/api/v1/notifications/${id}/read`, {
    method: 'PATCH',
    credentials: 'include',
  })
  if (!res.ok) throw new Error('Failed to mark notification as read')
}

export const Route = createFileRoute('/_authed/notifications')({
  loader: async (): Promise<NotificationsResponse> => {
    return fetchNotifications({ page: 1, limit: 20 })
  },
  component: NotificationsPage,
})

function NotificationsPage() {
  const initialData = Route.useLoaderData() as NotificationsResponse

  const [notificationsList, setNotificationsList] = useState<NotificationRow[]>(
    initialData.data ?? [],
  )
  const [meta, setMeta] = useState<PaginationMeta>(
    initialData.meta ?? { total: 0, page: 1, limit: 20 },
  )
  const [page, setPage] = useState(1)
  const [isLoading, setIsLoading] = useState(false)
  const navigate = useNavigate()

  const totalPages = Math.ceil((meta.total ?? 0) / (meta.limit ?? 20))

  async function loadPage(newPage: number) {
    setIsLoading(true)
    try {
      const data = await fetchNotifications({ page: newPage, limit: 20 })
      setNotificationsList(data.data ?? [])
      setMeta(data.meta)
      setPage(newPage)
    } finally {
      setIsLoading(false)
    }
  }

  async function handleMarkAllRead() {
    await markAllReadFn()
    setNotificationsList((prev) => prev.map((n) => ({ ...n, isRead: true })))
  }

  async function handleItemClick(notification: NotificationRow) {
    if (!notification.isRead) {
      await markOneFn(notification.id)
      setNotificationsList((prev) =>
        prev.map((n) => (n.id === notification.id ? { ...n, isRead: true } : n)),
      )
    }
    if (notification.entityType === 'achievement_points' && notification.entityId) {
      navigate({ to: '/points/$id', params: { id: notification.entityId } })
    }
  }

  return (
    <div className="space-y-4 p-4 max-w-3xl mx-auto">
      {/* Page header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 shrink-0">
            <Bell className="h-5 w-5 text-primary" />
          </div>
          <div>
            <h1 className="text-xl font-extrabold text-foreground">{m.nav_notifications()}</h1>
            <p className="text-xs font-medium text-muted-foreground">{meta.total} {m.nav_notifications().toLowerCase()}</p>
          </div>
        </div>
        <Button
          variant="outline"
          size="sm"
          className="rounded-xl border-border text-primary hover:bg-primary/8 hover:border-primary/40 font-semibold text-xs min-h-[36px] transition-all duration-200"
          onClick={handleMarkAllRead}
        >
          {m.notifications_mark_all_read()}
        </Button>
      </div>

      <div className="space-y-1">
        {isLoading ? (
          <div className="space-y-2">
            {Array.from({ length: 5 }).map((_, i) => (
              <div
                key={i}
                className="h-16 rounded-xl border border-border bg-primary/4 animate-pulse"
              />
            ))}
          </div>
        ) : notificationsList.length === 0 ? (
          <div className="rounded-2xl border border-border bg-card shadow-card flex flex-col items-center justify-center py-16 text-center gap-3">
            <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/8">
              <Bell className="h-7 w-7 text-primary/40" />
            </div>
            <p className="font-semibold text-muted-foreground">{m.notifications_empty()}</p>
          </div>
        ) : (
          notificationsList.map((notification) => (
            <button
              key={notification.id}
              type="button"
              className="card-hover block w-full text-left"
              onClick={() => handleItemClick(notification)}
            >
              <div
                className={cn(
                  'flex items-start gap-3 rounded-xl border border-border px-4 py-3 transition-colors hover:bg-primary/4 bg-card',
                  !notification.isRead && 'bg-primary/5 border-primary/15',
                )}
              >
                <div className="mt-0.5 shrink-0">
                  <NotificationIcon type={notification.type} />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium leading-snug text-foreground">{notification.title}</p>
                  {notification.body && (
                    <p className="text-xs text-muted-foreground mt-0.5 line-clamp-2">
                      {notification.body}
                    </p>
                  )}
                  <p className="text-xs text-muted-foreground mt-1">
                    {formatRelativeTime(new Date(notification.createdAt))}
                  </p>
                </div>
                {!notification.isRead && (
                  <div className="mt-1.5 shrink-0 h-2 w-2 rounded-full bg-primary" />
                )}
              </div>
            </button>
          ))
        )}
      </div>

      {totalPages > 1 && (
        <div className="flex items-center justify-center gap-2 pt-2">
          <Button
            variant="outline"
            size="sm"
            disabled={page <= 1 || isLoading}
            onClick={() => loadPage(page - 1)}
            className="rounded-xl border-border hover:bg-primary/6 hover:text-primary min-h-[36px]"
          >
            {m.common_previous()}
          </Button>
          <span className="rounded-xl bg-card border border-border px-3 py-1.5 text-sm font-semibold text-muted-foreground">
            {m.common_page_of({ page: String(page), total: String(totalPages) })}
          </span>
          <Button
            variant="outline"
            size="sm"
            disabled={page >= totalPages || isLoading}
            onClick={() => loadPage(page + 1)}
            className="rounded-xl border-border hover:bg-primary/6 hover:text-primary min-h-[36px]"
          >
            {m.common_next()}
          </Button>
        </div>
      )}
    </div>
  )
}
