// packages/web/src/routes/(authed)/redemptions/+page.svelte
<script lang="ts">
  import { Badge } from '$lib/components/ui/badge'
  import { Button } from '$lib/components/ui/button'
  import { userState } from '$lib/state/userState.svelte'
  import { api } from '$lib/api/client'
  import * as m from '$lib/paraglide/messages'
  import { Gift } from 'lucide-svelte'

  let { data } = $props()

  type RedemptionRow = {
    id: string
    rewardName: string
    rewardImageUrl: string | null
    pointsSpent: number
    status: 'pending' | 'approved' | 'rejected'
    rejectionReason: string | null
    approverName: string | null
    createdAt: string
    userName?: string
  }

  const isHrOrAdmin = $derived(userState.isHR)

  type Tab = 'mine' | 'pending'
  let activeTab = $state<Tab>('mine')
  let redemptions = $state<RedemptionRow[]>((data.redemptions.data ?? []) as RedemptionRow[])
  let isLoading = $state(false)
  let isSubmitting = $state(false)
  let rejectOpen = $state(false)
  let selectedId = $state<string | null>(null)
  let rejectionReason = $state('')

  const STATUS_CLASS: Record<string, string> = {
    pending:
      'bg-[#F4C144]/15 text-[#a07700] border-[#F4C144]/30 dark:bg-yellow-900/30 dark:text-yellow-300 dark:border-yellow-800/40',
    approved:
      'bg-emerald-50 text-emerald-700 border-emerald-200/70 dark:bg-emerald-900/30 dark:text-emerald-400 dark:border-emerald-800/50',
    rejected:
      'bg-red-50 text-red-700 border-red-200/70 dark:bg-red-900/30 dark:text-red-400 dark:border-red-800/50',
  }

  function statusLabel(s: string) {
    if (s === 'approved') return m.status_approved()
    if (s === 'rejected') return m.status_rejected()
    return m.status_pending()
  }

  function formatDate(iso: string) {
    return new Date(iso).toLocaleDateString('id-ID', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
    })
  }

  async function loadTab(tab: Tab) {
    isLoading = true
    try {
      const params = tab === 'mine' ? '?mine=true' : '?status=pending'
      const res = await fetch(`/api/v1/redemptions${params}`, { credentials: 'include' })
      const json = await res.json()
      redemptions = (json.data ?? []) as RedemptionRow[]
    } finally {
      isLoading = false
    }
  }

  function handleTabChange(tab: Tab) {
    activeTab = tab
    loadTab(tab)
  }

  async function handleApprove(id: string) {
    isSubmitting = true
    try {
      await api.api.v1.redemptions[id].approve.post({})
      await loadTab(activeTab)
    } finally {
      isSubmitting = false
    }
  }

  function openReject(id: string) {
    selectedId = id
    rejectionReason = ''
    rejectOpen = true
  }

  async function handleRejectConfirm() {
    if (!selectedId) return
    isSubmitting = true
    try {
      await api.api.v1.redemptions[selectedId].reject.post({
        rejectionReason: rejectionReason.trim() || undefined,
      })
      rejectOpen = false
      selectedId = null
      await loadTab(activeTab)
    } finally {
      isSubmitting = false
    }
  }
</script>

<div class="mx-auto max-w-2xl space-y-5 p-4 page-transition">
  <!-- Header -->
  <div class="flex items-center gap-3 pt-2">
    <div
      class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-[#F4C144] to-[#FFD97D] shadow-[0_4px_12px_rgba(244,193,68,0.25)]"
    >
      <Gift class="h-5 w-5 text-[#7a5800]" />
    </div>
    <div>
      <h1 class="text-xl font-extrabold text-foreground">{m.redemptions_title()}</h1>
      <p class="text-[13px] font-medium text-muted-foreground">{m.redemptions_my_requests()}</p>
    </div>
  </div>

  <!-- Tab switcher -->
  <div class="flex gap-1.5 rounded-2xl border border-border bg-card p-1.5 shadow-card">
    <button
      type="button"
      class="flex flex-1 min-h-[44px] items-center justify-center gap-1.5 rounded-xl px-3 py-2.5 text-sm font-bold transition-all duration-200 {activeTab ===
      'mine'
        ? 'border border-[#F4C144]/30 bg-gradient-to-br from-[#F4C144]/18 to-[#F4C144]/8 text-[#a07700] shadow-[0_2px_8px_rgba(244,193,68,0.20)] dark:text-yellow-300'
        : 'text-muted-foreground hover:text-foreground'}"
      onclick={() => handleTabChange('mine')}
    >
      <Gift class="h-4 w-4" />
      {m.redemptions_my_requests()}
    </button>
    {#if isHrOrAdmin}
      <button
        type="button"
        class="flex flex-1 min-h-[44px] items-center justify-center gap-1.5 rounded-xl px-3 py-2.5 text-sm font-bold transition-all duration-200 {activeTab ===
        'pending'
          ? 'border border-primary/30 bg-gradient-to-br from-primary/18 to-primary/8 text-primary shadow-[0_2px_8px_rgba(50,95,236,0.20)]'
          : 'text-muted-foreground hover:text-foreground'}"
        onclick={() => handleTabChange('pending')}
      >
        <Gift class="h-4 w-4" />
        {m.redemptions_pending_approval()}
      </button>
    {/if}
  </div>

  <!-- Card list -->
  <div class="space-y-3">
    {#if isLoading}
      {#each [0, 1, 2, 3] as _i}
        <div class="h-24 animate-pulse rounded-xl border border-border bg-card shadow-card"></div>
      {/each}
    {:else if redemptions.length === 0}
      <div class="flex flex-col items-center justify-center gap-3 py-16 text-center">
        <div class="flex h-14 w-14 items-center justify-center rounded-full bg-[#F4C144]/12">
          <Gift class="h-7 w-7 text-[#F4C144]" />
        </div>
        <p class="text-sm font-medium text-muted-foreground">{m.redemptions_empty()}</p>
      </div>
    {:else}
      {#each redemptions as item (item.id)}
        <div
          class="flex items-start gap-3 rounded-xl border border-border bg-card px-4 py-3 shadow-card transition-all duration-200 hover:shadow-[0_4px_16px_rgba(0,0,0,0.10)]"
        >
          <!-- Thumbnail -->
          <div
            class="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl border border-border bg-primary/8"
          >
            {#if item.rewardImageUrl}
              <img
                src={item.rewardImageUrl}
                alt={item.rewardName}
                class="h-full w-full object-cover"
              />
            {:else}
              <Gift class="h-6 w-6 text-primary/50" />
            {/if}
          </div>

          <!-- Info -->
          <div class="min-w-0 flex-1">
            <div class="flex items-start justify-between gap-2">
              <p class="line-clamp-1 text-sm font-semibold leading-snug text-foreground">
                {item.rewardName}
              </p>
              <Badge
                variant="outline"
                class="shrink-0 text-xs font-medium {STATUS_CLASS[item.status] ?? ''}"
              >
                {statusLabel(item.status)}
              </Badge>
            </div>

            {#if activeTab === 'pending' && item.userName}
              <p class="mt-0.5 text-xs text-muted-foreground">
                {m.redemptions_requested_by()}
                <span class="font-semibold text-foreground/80">{item.userName}</span>
              </p>
            {/if}

            <p class="mt-0.5 text-xs font-semibold text-primary">
              {item.pointsSpent} {m.points_poin_aha()}
            </p>

            <div class="mt-1 flex flex-wrap items-center gap-2">
              <span class="text-xs text-muted-foreground/60">{formatDate(item.createdAt)}</span>
              {#if item.approverName && item.status !== 'pending'}
                <span class="text-xs text-muted-foreground/60">
                  ·
                  {item.status === 'approved'
                    ? m.redemptions_approved_by()
                    : m.redemptions_rejected_by()}
                  <span class="font-medium text-muted-foreground">{item.approverName}</span>
                </span>
              {/if}
              {#if item.rejectionReason}
                <span class="text-xs italic text-destructive">"{item.rejectionReason}"</span>
              {/if}
            </div>

            <!-- HR/Admin actions -->
            {#if activeTab === 'pending' && item.status === 'pending' && isHrOrAdmin}
              <div class="mt-2 flex gap-2">
                <Button
                  size="sm"
                  class="h-7 rounded-lg px-3 text-xs font-semibold bg-gradient-to-br from-[#325FEC] to-[#759EEE] text-white"
                  disabled={isSubmitting}
                  onclick={() => handleApprove(item.id)}
                >
                  {m.common_approve()}
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  class="h-7 rounded-lg border-destructive/25 px-3 text-xs font-semibold text-destructive hover:bg-destructive/8"
                  disabled={isSubmitting}
                  onclick={() => openReject(item.id)}
                >
                  {m.common_reject()}
                </Button>
              </div>
            {/if}
          </div>
        </div>
      {/each}
    {/if}
  </div>
</div>

<!-- Reject dialog -->
{#if rejectOpen}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
    role="dialog"
    aria-modal="true"
  >
    <div class="w-full max-w-sm rounded-2xl border border-border bg-card p-5 shadow-xl">
      <h2 class="mb-4 text-base font-bold text-foreground">{m.redemptions_reject_title()}</h2>
      <div class="space-y-2">
        <label class="text-sm font-medium text-foreground" for="rejection-reason">
          {m.redemptions_reject_reason_label()}
        </label>
        <textarea
          id="rejection-reason"
          class="w-full resize-none rounded-lg border border-input bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary"
          rows="3"
          placeholder={m.redemptions_reject_placeholder()}
          bind:value={rejectionReason}
        ></textarea>
      </div>
      <div class="mt-4 flex justify-end gap-2">
        <Button
          variant="outline"
          size="sm"
          disabled={isSubmitting}
          onclick={() => (rejectOpen = false)}
        >
          {m.common_cancel()}
        </Button>
        <Button
          size="sm"
          class="bg-destructive text-destructive-foreground hover:bg-destructive/90"
          disabled={isSubmitting}
          onclick={handleRejectConfirm}
        >
          {isSubmitting ? m.redemptions_rejecting() : m.redemptions_confirm_reject()}
        </Button>
      </div>
    </div>
  </div>
{/if}

// src/routes/_authed/redemptions.tsx
import { useState } from 'react'
import { createFileRoute, useRouter } from '@tanstack/react-router'
import * as m from '~/paraglide/messages'
import { Gift } from 'lucide-react'
import { Button } from '~/components/ui/button'
import { Badge } from '~/components/ui/badge'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '~/components/ui/dialog'
import { cn } from '~/lib/utils'
import {
  listRedemptionsFn,
  approveRedemptionFn,
  rejectRedemptionFn,
} from '~/server/functions/redemptions'

type RedemptionRow = {
  id: string
  userId: string
  userName: string
  rewardId: string
  rewardName: string
  rewardImageUrl: string | null
  pointsSpent: number
  status: 'pending' | 'approved' | 'rejected'
  rejectionReason: string | null
  approverName: string | null
  createdAt: string
  resolvedAt: string | null
}

type Tab = 'mine' | 'pending'

const redemptionStatusConfig: Record<
  'pending' | 'approved' | 'rejected',
  { className: string }
> = {
  pending: {
    className: 'bg-yellow-100 text-yellow-700 border-yellow-200',
  },
  approved: {
    className: 'bg-green-100 text-green-700 border-green-200',
  },
  rejected: {
    className: 'bg-red-100 text-red-700 border-red-200',
  },
}

function redemptionStatusLabel(status: 'pending' | 'approved' | 'rejected'): string {
  if (status === 'approved') return m.status_approved()
  if (status === 'rejected') return m.status_rejected()
  return m.status_pending()
}

function RedemptionStatusBadge({
  status,
  className,
}: {
  readonly status: 'pending' | 'approved' | 'rejected'
  readonly className?: string
}) {
  const config = redemptionStatusConfig[status]
  return (
    <Badge
      variant="outline"
      className={cn('text-xs font-medium', config.className, className)}
    >
      {redemptionStatusLabel(status)}
    </Badge>
  )
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('id-ID', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  })
}

export const Route = createFileRoute('/_authed/redemptions')({
  loader: async () => {
    const data = await listRedemptionsFn({ data: { mine: true } })
    return data
  },
  component: RedemptionsPage,
  pendingComponent: RedemptionsSkeleton,
})

function RedemptionsSkeleton() {
  return (
    <div className="max-w-2xl mx-auto p-4 space-y-6 animate-pulse">
      <div className="h-6 w-32 rounded bg-muted" />
      <div className="flex gap-2 border-b border-border pb-2">
        <div className="h-8 w-28 rounded bg-muted" />
        <div className="h-8 w-36 rounded bg-muted" />
      </div>
      <div className="space-y-3">
        {Array.from({ length: 4 }).map((_, i) => (
          <div key={i} className="h-24 rounded-xl border border-border bg-white" />
        ))}
      </div>
    </div>
  )
}

function RedemptionsPage() {
  const initialData = Route.useLoaderData()
  const { session } = Route.useRouteContext()
  const router = useRouter()

  const role = session?.appUser?.role ?? 'employee'
  const isHrOrAdmin = role === 'hr' || role === 'admin'

  const [activeTab, setActiveTab] = useState<Tab>('mine')
  const [redemptions, setRedemptions] = useState<RedemptionRow[]>(
    (initialData.redemptions ?? []) as RedemptionRow[],
  )
  const [isLoading, setIsLoading] = useState(false)
  const [rejectDialogOpen, setRejectDialogOpen] = useState(false)
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [rejectionReason, setRejectionReason] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)

  async function loadTab(tab: Tab) {
    setIsLoading(true)
    try {
      const params =
        tab === 'mine'
          ? { mine: true }
          : { status: 'pending' as const }
      const data = await listRedemptionsFn({ data: params })
      setRedemptions((data.redemptions ?? []) as RedemptionRow[])
    } finally {
      setIsLoading(false)
    }
  }

  function handleTabChange(tab: Tab) {
    setActiveTab(tab)
    loadTab(tab)
  }

  async function handleApprove(id: string) {
    setIsSubmitting(true)
    try {
      await approveRedemptionFn({ data: { id } })
      await router.invalidate()
      await loadTab(activeTab)
    } finally {
      setIsSubmitting(false)
    }
  }

  function openRejectDialog(id: string) {
    setSelectedId(id)
    setRejectionReason('')
    setRejectDialogOpen(true)
  }

  async function handleRejectConfirm() {
    if (!selectedId) return
    setIsSubmitting(true)
    try {
      await rejectRedemptionFn({
        data: { id: selectedId, rejectionReason: rejectionReason.trim() || undefined },
      })
      setRejectDialogOpen(false)
      setSelectedId(null)
      await router.invalidate()
      await loadTab(activeTab)
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="max-w-2xl mx-auto p-4 space-y-6">
      <h1 className="text-xl font-bold text-[#1D388B]">{m.redemptions_title()}</h1>

      {/* Tab bar */}
      <div className="flex gap-2 border-b border-border">
        <button
          type="button"
          className={cn(
            'px-4 py-2 text-sm font-medium transition-colors border-b-2 -mb-px',
            activeTab === 'mine'
              ? 'border-[#325FEC] text-[#325FEC]'
              : 'border-transparent text-muted-foreground hover:text-foreground',
          )}
          onClick={() => handleTabChange('mine')}
        >
          {m.redemptions_my_requests()}
        </button>
        {isHrOrAdmin && (
          <button
            type="button"
            className={cn(
              'px-4 py-2 text-sm font-medium transition-colors border-b-2 -mb-px',
              activeTab === 'pending'
                ? 'border-[#325FEC] text-[#325FEC]'
                : 'border-transparent text-muted-foreground hover:text-foreground',
            )}
            onClick={() => handleTabChange('pending')}
          >
            {m.redemptions_pending_approval()}
          </button>
        )}
      </div>

      {/* Card list */}
      <div className="space-y-3">
        {isLoading ? (
          Array.from({ length: 4 }).map((_, i) => (
            <div
              key={i}
              className="h-24 rounded-xl border border-border bg-muted/50 animate-pulse"
            />
          ))
        ) : redemptions.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-center gap-3">
            <Gift className="h-10 w-10 text-muted-foreground/40" />
            <p className="text-muted-foreground">{m.redemptions_empty()}</p>
          </div>
        ) : (
          redemptions.map((item) => (
            <div
              key={item.id}
              className="flex items-start gap-3 rounded-xl border border-border bg-white px-4 py-3"
            >
              {/* Thumbnail */}
              <div className="shrink-0 h-12 w-12 rounded-lg bg-muted flex items-center justify-center overflow-hidden">
                {item.rewardImageUrl ? (
                  <img
                    src={item.rewardImageUrl}
                    alt={item.rewardName}
                    className="h-full w-full object-cover"
                  />
                ) : (
                  <Gift className="h-6 w-6 text-muted-foreground/60" />
                )}
              </div>

              {/* Info */}
              <div className="flex-1 min-w-0">
                <div className="flex items-start justify-between gap-2">
                  <p className="text-sm font-semibold text-[#1D388B] leading-snug line-clamp-1">
                    {item.rewardName}
                  </p>
                  <RedemptionStatusBadge status={item.status} />
                </div>

                {activeTab === 'pending' && (
                  <p className="text-xs text-muted-foreground mt-0.5">
                    {m.redemptions_requested_by()}{' '}
                    <span className="font-medium text-foreground">{item.userName}</span>
                  </p>
                )}

                <p className="text-xs font-medium text-[#325FEC] mt-0.5">
                  {item.pointsSpent} {m.points_poin_aha()}
                </p>

                <div className="flex items-center gap-2 mt-1 flex-wrap">
                  <span className="text-xs text-muted-foreground">
                    {formatDate(item.createdAt)}
                  </span>
                  {item.approverName && item.status !== 'pending' && (
                    <span className="text-xs text-muted-foreground">
                      · {item.status === 'approved' ? m.redemptions_approved_by() : m.redemptions_rejected_by()}{' '}
                      <span className="font-medium text-foreground">{item.approverName}</span>
                    </span>
                  )}
                  {item.rejectionReason && (
                    <span className="text-xs text-red-600 italic">
                      "{item.rejectionReason}"
                    </span>
                  )}
                </div>

                {/* HR/Admin actions for pending tab */}
                {activeTab === 'pending' && item.status === 'pending' && (
                  <div className="flex gap-2 mt-2">
                    <Button
                      size="sm"
                      className="h-7 px-3 text-xs bg-green-600 hover:bg-green-700 text-white"
                      disabled={isSubmitting}
                      onClick={() => handleApprove(item.id)}
                    >
                      {m.common_approve()}
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      className="h-7 px-3 text-xs border-red-200 text-red-600 hover:bg-red-50 hover:text-red-700"
                      disabled={isSubmitting}
                      onClick={() => openRejectDialog(item.id)}
                    >
                      {m.common_reject()}
                    </Button>
                  </div>
                )}
              </div>
            </div>
          ))
        )}
      </div>

      {/* Reject dialog */}
      <Dialog open={rejectDialogOpen} onOpenChange={setRejectDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>{m.redemptions_reject_title()}</DialogTitle>
          </DialogHeader>
          <div className="space-y-2 py-2">
            <label className="text-sm font-medium text-foreground" htmlFor="rejection-reason">
              {m.redemptions_reject_reason_label()}
            </label>
            <textarea
              id="rejection-reason"
              className="w-full rounded-lg border border-input bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-[#325FEC] resize-none"
              rows={3}
              placeholder={m.redemptions_reject_placeholder()}
              value={rejectionReason}
              onChange={(e) => setRejectionReason(e.target.value)}
            />
          </div>
          <DialogFooter className="gap-2">
            <Button
              variant="outline"
              size="sm"
              disabled={isSubmitting}
              onClick={() => setRejectDialogOpen(false)}
            >
              {m.common_cancel()}
            </Button>
            <Button
              size="sm"
              className="bg-red-600 hover:bg-red-700 text-white"
              disabled={isSubmitting}
              onClick={handleRejectConfirm}
            >
              {isSubmitting ? m.redemptions_rejecting() : m.redemptions_confirm_reject()}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
