// src/components/theme-toggle.tsx
import { Moon, Sun } from 'lucide-react'
import { useTheme } from '~/components/theme-provider'

export function ThemeToggle() {
  const { theme, setTheme } = useTheme()

  return (
    <button
      type="button"
      onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')}
      className="flex h-9 w-9 items-center justify-center rounded-full text-muted-foreground hover:bg-[#325FEC]/8 hover:text-[#325FEC] transition-colors"
      aria-label={theme === 'light' ? 'Switch to dark mode' : 'Switch to light mode'}
    >
      {theme === 'light' ? <Sun className="h-4.5 w-4.5" /> : <Moon className="h-4.5 w-4.5" />}
    </button>
  )
}

// packages/web/src/lib/components/ThemeToggle.svelte
<script lang="ts">
  import { Sun, Moon, Monitor } from 'lucide-svelte'
  import { uiState } from '$lib/state/uiState.svelte'

  const CYCLE: Array<'light' | 'dark' | 'system'> = ['light', 'dark', 'system']

  function cycleTheme() {
    const idx = CYCLE.indexOf(uiState.theme)
    const next = CYCLE[(idx + 1) % CYCLE.length]
    uiState.setTheme(next)
  }

  const label = $derived(
    uiState.theme === 'light'
      ? 'Switch to dark mode'
      : uiState.theme === 'dark'
        ? 'Switch to system mode'
        : 'Switch to light mode',
  )
</script>

<button
  type="button"
  onclick={cycleTheme}
  class="flex h-9 w-9 items-center justify-center rounded-full text-muted-foreground hover:bg-primary/8 hover:text-foreground transition-colors"
  aria-label={label}
>
  {#if uiState.theme === 'light'}
    <Sun class="h-4 w-4" />
  {:else if uiState.theme === 'dark'}
    <Moon class="h-4 w-4" />
  {:else}
    <Monitor class="h-4 w-4" />
  {/if}
</button>
