// packages/web/src/routes/(authed)/points/new/bintang/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { toast } from 'svelte-sonner'
  import { api } from '$lib/api/client'
  import { uploadScreenshot } from '$lib/api/uploads'
  import { userState } from '$lib/state/userState.svelte'
  import { Button } from '$lib/components/ui/button'
  import EmployeeSelector from '$lib/components/points/EmployeeSelector.svelte'
  import { Star, AlertTriangle, ChevronRight } from 'lucide-svelte'
  import * as m from '$lib/paraglide/messages'
  import { getErrorMessage } from '$lib/api/client'

  const user = $derived(userState.current)
  const isSelfOnly = $derived(!(user?.canSubmitPoints ?? false))

  let userId = $state<string>('')
  let reason = $state('')
  let relatedStaff = $state('')
  let screenshotFile = $state<File | undefined>()
  let screenshotPreview = $state<string | undefined>()
  let isSubmitting = $state(false)
  let error = $state<string | null>(null)

  // Initialise userId for self-only after user resolves
  $effect(() => {
    if (isSelfOnly && user?.id) userId = user.id
  })

  function handleFileChange(e: Event) {
    const file = (e.target as HTMLInputElement).files?.[0]
    if (file) {
      screenshotFile = file
      screenshotPreview = URL.createObjectURL(file)
    }
  }

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault()
    error = null

    if (!userId) { error = m.form_error_select_employee(); return }
    if (!reason.trim()) { error = m.form_error_provide_reason(); return }
    if (!screenshotFile) { error = m.form_error_screenshot_required(); return }

    isSubmitting = true
    try {
      const screenshotUrl = await uploadScreenshot(screenshotFile)
      const payload = {
        userId,
        categoryCode: 'BINTANG',
        points: 1,
        reason: reason.trim(),
        relatedStaff: relatedStaff.trim() || undefined,
        screenshotUrl,
      }
      const result = await api.api.v1.points.post(payload as never)
      if (result.error) {
        error = getErrorMessage(result.error, m.form_error_submission_failed())
        return
      }
      toast.success(m.bintang_form_submit())
      goto('/points')
    } catch (err) {
      error = err instanceof Error ? err.message : m.form_error_submission_failed()
    } finally {
      isSubmitting = false
    }
  }
</script>

<div class="min-h-screen bg-background">
  <!-- Page header -->
  <div class="bg-[#1D388B] px-4 pt-5 pb-6">
    <div class="max-w-lg mx-auto">
      <div class="flex items-center gap-1.5 text-white/60 text-xs font-medium mb-3">
        <a href="/points" class="hover:text-white/80 transition-colors">Poin</a>
        <ChevronRight class="w-3 h-3" />
        <span class="text-white/90">Catat Bintang</span>
      </div>
      <div class="flex items-start gap-3">
        <div
          class="flex-shrink-0 flex items-center justify-center w-11 h-11 rounded-xl bg-[#F4C144]/20 border border-[#F4C144]/30 mt-0.5"
        >
          <Star class="w-5 h-5 text-[#F4C144]" />
        </div>
        <div>
          <h1 class="text-xl font-bold text-white leading-tight">{m.bintang_form_title()}</h1>
          <p class="text-white/60 text-xs mt-1">
            Isi semua bagian dengan teliti sebelum mengirim
          </p>
        </div>
      </div>
    </div>
  </div>

  <!-- Form body -->
  <div class="max-w-lg mx-auto px-4 py-5 space-y-4">
    <form onsubmit={handleSubmit} class="space-y-4">

      <!-- Step 1: Employee -->
      <div class="rounded-xl border border-border bg-card overflow-hidden">
        <div class="flex items-center gap-2.5 px-4 py-3 border-b border-border bg-muted/40">
          <span
            class="flex-shrink-0 flex items-center justify-center w-5 h-5 rounded-full bg-[#D4962A] text-white text-[10px] font-bold leading-none"
          >1</span>
          <span class="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
            {m.form_staff_name()}
          </span>
        </div>
        <div class="p-4">
          {#if isSelfOnly}
            <div
              class="flex h-10 w-full items-center rounded-lg border border-border bg-muted/50 px-3 text-sm text-muted-foreground"
            >
              {user?.name ?? ''}
            </div>
          {:else}
            <EmployeeSelector
              value={userId}
              onChange={(id) => (userId = id)}
              excludeId={user?.role === 'leader' ? (user?.id ?? undefined) : undefined}
            />
          {/if}
        </div>
      </div>

      <!-- Step 2: Action / Reason -->
      <div class="rounded-xl border border-border bg-card overflow-hidden">
        <div class="flex items-center gap-2.5 px-4 py-3 border-b border-border bg-muted/40">
          <span
            class="flex-shrink-0 flex items-center justify-center w-5 h-5 rounded-full bg-[#D4962A] text-white text-[10px] font-bold leading-none"
          >2</span>
          <span class="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
            {m.bintang_form_action()}
          </span>
        </div>
        <div class="p-4">
          <textarea
            class="flex min-h-28 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#F4C144]/40 focus-visible:border-[#F4C144]/50 transition-colors resize-none"
            placeholder={m.bintang_form_action_placeholder()}
            bind:value={reason}
            maxlength={1000}
          ></textarea>
          <div class="flex justify-end mt-1">
            <span class="text-[10px] text-muted-foreground">{reason.length}/1000</span>
          </div>
        </div>
      </div>

      <!-- Step 3: Related staff (optional) -->
      <div class="rounded-xl border border-border bg-card overflow-hidden">
        <div class="flex items-center gap-2.5 px-4 py-3 border-b border-border bg-muted/40">
          <span
            class="flex-shrink-0 flex items-center justify-center w-5 h-5 rounded-full bg-[#D4962A] text-white text-[10px] font-bold leading-none"
          >3</span>
          <span class="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
            {m.form_related_staff()}
          </span>
        </div>
        <div class="p-4">
          <input
            type="text"
            class="flex h-10 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#F4C144]/40 focus-visible:border-[#F4C144]/50 transition-colors"
            placeholder={m.form_related_staff_placeholder()}
            bind:value={relatedStaff}
            maxlength={500}
          />
        </div>
      </div>

      <!-- Step 4: Screenshot (required) -->
      <div class="rounded-xl border border-border bg-card overflow-hidden">
        <div class="flex items-center gap-2.5 px-4 py-3 border-b border-border bg-muted/40">
          <span
            class="flex-shrink-0 flex items-center justify-center w-5 h-5 rounded-full bg-[#D4962A] text-white text-[10px] font-bold leading-none"
          >4</span>
          <span class="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
            {m.form_screenshot_required()}
          </span>
        </div>
        <div class="p-4 space-y-2">
          <label
            class="flex flex-col items-center justify-center w-full h-32 border-2 border-dashed border-border rounded-xl cursor-pointer hover:bg-muted/30 transition-colors"
          >
            <span class="text-sm text-muted-foreground">
              {screenshotFile ? screenshotFile.name : 'Click to upload screenshot'}
            </span>
            <input type="file" accept="image/*" class="hidden" onchange={handleFileChange} />
          </label>
          {#if screenshotPreview}
            <div class="aspect-video rounded-xl overflow-hidden border border-border">
              <img src={screenshotPreview} alt="Preview" class="object-cover w-full h-full" />
            </div>
          {/if}
        </div>
      </div>

      {#if isSelfOnly}
        <div
          class="flex items-start gap-2.5 rounded-lg border border-[#F4C144]/40 bg-amber-50 px-3 py-2.5"
        >
          <Star class="w-4 h-4 text-[#D4962A] mt-0.5 flex-shrink-0" />
          <p class="text-sm text-amber-800 leading-snug">{m.form_pending_approval()}</p>
        </div>
      {/if}

      {#if error}
        <div
          class="flex items-start gap-2.5 rounded-lg border border-destructive/30 bg-destructive/5 px-3 py-2.5"
        >
          <AlertTriangle class="w-4 h-4 text-destructive mt-0.5 flex-shrink-0" />
          <p class="text-sm text-destructive leading-snug">{error}</p>
        </div>
      {/if}

      <Button
        type="submit"
        disabled={isSubmitting}
        class="w-full btn-gradient-gold text-[#1D388B] font-semibold h-11 rounded-xl shadow-md"
      >
        {isSubmitting ? m.common_submitting() : m.bintang_form_submit()}
      </Button>

      <p class="text-center text-[11px] text-muted-foreground pb-2">
        Bintang yang tercatat akan berkontribusi pada rekam jejak anggota
      </p>
    </form>
  </div>
</div>

// src/routes/_authed/points/new/bintang.tsx
import { useState } from 'react'
import { createFileRoute, useRouter } from '@tanstack/react-router'
import { Star, AlertTriangle, ChevronRight } from 'lucide-react'
import * as m from '~/paraglide/messages'
import { Button } from '~/components/ui/button'
import { EmployeeSelector } from '~/components/points/employee-selector'
import { FileUpload } from '~/components/ui/file-upload'
import { getPointsLookupDataFn, submitPointFn } from '~/server/functions/points'
import { uploadFile } from '~/lib/upload'
import type { UserRole } from '~/shared/constants'

export const Route = createFileRoute('/_authed/points/new/bintang')({
  loader: async () => {
    const data = await getPointsLookupDataFn()
    return data
  },
  component: BintangForm,
})

function StepBadge({ n }: { n: number }) {
  return (
    <span className="flex-shrink-0 flex items-center justify-center w-5 h-5 rounded-full bg-[#D4962A] text-white text-[10px] font-bold leading-none">
      {n}
    </span>
  )
}

function SectionCard({
  step,
  title,
  children,
}: {
  step: number
  title: string
  children: React.ReactNode
}) {
  return (
    <div className="rounded-xl border border-border bg-card shadow-[var(--shadow-card)] overflow-hidden">
      <div className="flex items-center gap-2.5 px-4 py-3 border-b border-border bg-muted/40">
        <StepBadge n={step} />
        <span className="text-xs font-semibold tracking-wide text-muted-foreground uppercase">
          {title}
        </span>
      </div>
      <div className="p-4">{children}</div>
    </div>
  )
}

function BintangForm() {
  const { employees } = Route.useLoaderData()
  const { session } = Route.useRouteContext()
  const router = useRouter()
  const userRole = (session?.appUser?.role ?? 'employee') as UserRole

  const isEmployee = userRole === 'employee'
  const [userId, setUserId] = useState(isEmployee ? (session?.appUser?.id ?? '') : '')
  const [reason, setReason] = useState('')
  const [relatedStaff, setRelatedStaff] = useState('')
  const [screenshotFile, setScreenshotFile] = useState<File | undefined>()
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setError(null)

    if (!userId) return setError(m.form_error_select_employee())
    if (!reason.trim()) return setError(m.form_error_provide_reason())
    if (!screenshotFile) return setError(m.form_error_screenshot_required())

    setIsSubmitting(true)
    try {
      const screenshotUrl = await uploadFile(screenshotFile)
      await submitPointFn({
        data: {
          userId,
          categoryCode: 'BINTANG',
          points: 1,
          reason: reason.trim(),
          relatedStaff: relatedStaff.trim() || undefined,
          screenshotUrl,
        },
      })
      await router.invalidate()
      router.navigate({ to: '/points' })
    } catch (err) {
      setError(err instanceof Error ? err.message : m.form_error_submission_failed())
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Page header */}
      <div className="bg-[#1D388B] px-4 pt-5 pb-6">
        <div className="max-w-lg mx-auto">
          <div className="flex items-center gap-1.5 text-sky-blue/70 text-xs font-medium mb-3">
            <span>Poin</span>
            <ChevronRight className="w-3 h-3" />
            <span className="text-white/90">Catat Bintang</span>
          </div>
          <div className="flex items-start gap-3">
            <div className="flex-shrink-0 flex items-center justify-center w-11 h-11 rounded-xl bg-[#F4C144]/20 border border-[#F4C144]/30 mt-0.5">
              <Star className="w-5 h-5 text-[#F4C144]" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-white leading-tight">
                {m.bintang_form_title()}
              </h1>
              <p className="text-sky-blue/70 text-xs mt-1">
                Isi semua bagian dengan teliti sebelum mengirim
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Form body */}
      <div className="max-w-lg mx-auto px-4 py-5 space-y-4 page-transition">
        <form onSubmit={handleSubmit} className="space-y-4">

          {/* Step 1 — Employee */}
          <SectionCard step={1} title={m.form_staff_name()}>
            {isEmployee ? (
              <div className="flex h-10 w-full items-center rounded-lg border border-border bg-muted/50 px-3 text-sm text-muted-foreground">
                {session?.appUser?.name ?? session?.user?.name}
              </div>
            ) : (
              <EmployeeSelector
                employees={employees}
                value={userId}
                onChange={setUserId}
                excludeId={userRole === 'leader' ? session?.appUser?.id : undefined}
              />
            )}
          </SectionCard>

          {/* Step 2 — Action / Reason */}
          <SectionCard step={2} title={m.bintang_form_action()}>
            <textarea
              id="reason"
              className="flex min-h-28 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#F4C144]/40 focus-visible:border-[#F4C144]/50 transition-colors resize-none"
              placeholder={m.bintang_form_action_placeholder()}
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              maxLength={1000}
            />
            <div className="flex justify-end mt-1">
              <span className="text-[10px] text-muted-foreground">{reason.length}/1000</span>
            </div>
          </SectionCard>

          {/* Step 3 — Related staff (optional) */}
          <SectionCard step={3} title={m.form_related_staff()}>
            <input
              id="relatedStaff"
              className="flex h-10 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#F4C144]/40 focus-visible:border-[#F4C144]/50 transition-colors"
              placeholder={m.form_related_staff_placeholder()}
              value={relatedStaff}
              onChange={(e) => setRelatedStaff(e.target.value)}
              maxLength={500}
            />
          </SectionCard>

          {/* Step 4 — Screenshot (required) */}
          <SectionCard step={4} title={m.form_screenshot_required()}>
            <FileUpload
              value={screenshotFile}
              onChange={setScreenshotFile}
              required
            />
          </SectionCard>

          {/* Pending approval notice for employees */}
          {isEmployee && (
            <div className="flex items-start gap-2.5 rounded-lg border border-[#F4C144]/40 bg-amber-50 px-3 py-2.5">
              <Star className="w-4 h-4 text-[#D4962A] mt-0.5 flex-shrink-0" />
              <p className="text-sm text-amber-800 leading-snug">{m.form_pending_approval()}</p>
            </div>
          )}

          {/* Error */}
          {error && (
            <div className="flex items-start gap-2.5 rounded-lg border border-destructive/30 bg-destructive/5 px-3 py-2.5">
              <AlertTriangle className="w-4 h-4 text-destructive mt-0.5 flex-shrink-0" />
              <p className="text-sm text-destructive leading-snug">{error}</p>
            </div>
          )}

          {/* Submit */}
          <Button
            type="submit"
            disabled={isSubmitting}
            className="w-full bg-[#F4C144] hover:bg-[#D4962A] text-[#1D388B] font-semibold h-11 rounded-xl shadow-md transition-colors"
          >
            {isSubmitting ? m.common_submitting() : m.bintang_form_submit()}
          </Button>

          <p className="text-center text-[11px] text-muted-foreground pb-2">
            Bintang yang tercatat akan berkontribusi pada rekam jejak anggota
          </p>
        </form>
      </div>
    </div>
  )
}
